### PR TITLE
fix issue when scanning a local image with the snyk containerized pro…

### LINKED ISSUE #151: Linux docker scan not working for locally built/cache image
**Description**
On Ubuntu VM (tested on both 20.04.1 and 18.04.5) docker scan is erroring trying to scan an image I built locally with the following:

```bash
vagrant@ubuntu-focal:~/goof$ docker image ls
REPOSITORY   TAG       IMAGE ID       CREATED         SIZE
goof         latest    5e25129436a9   4 minutes ago   1.09GB
snyk/snyk    <none>    6fda31b366a0   7 weeks ago     113MB
node         14.1.0    a511eb5c14ec   11 months ago   941MB
vagrant@ubuntu-focal:~/goof$ docker scan goof
Failed to scan image "goof". Please make sure the image and/or repository exist, and that you are using the correct credentials.
vagrant@ubuntu-focal:~/goof$ docker scan goof:latest
Failed to scan image "goof:latest". Please make sure the image and/or repository exist, and that you are using the correct credentials.
```

**Steps to reproduce the issue:**
1. Build an image
2. `docker scan [image]`

**Describe the results you received:**
Getting the error shown above

**Describe the results you expected:**
Snyk scan results

**Additional information you deem important (e.g. issue happens only occasionally):**
Have done a `docker scan --login` successfully previously.
Also have tried with or without having done a `docker login`

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker scan --version`:**

```
Version:    v0.7.0
Git commit: 0b3c564
Provider:   Snyk (1.461.0 (standalone))
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 15
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-56-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 5.807GiB
 Name: ubuntu-focal
 ID: UY3G:XY2P:Y4MF:WF52:BD7B:MFKG:WF6W:DQKK:SVVQ:XHK3:JKO7:H2EW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: ericsmalling
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox as defined in https://github.com/ericsmalling/vagrantfiles/blob/main/docker-ce/Vagrantfile
Also seeing the same behavior on an AWS Cloud9 instance running on Ubuntu 18.04.5 instance.

### PR DESCRIPTION
**Pull request by glours**
…vider

Signed-off-by: Guillaume Lours <guillaume.lours@docker.com>

fixes #151 

**- What I did**
Use the `snyk/snyk:docker` image instead of the `snyk/snyk:alpine` one

**- How I did it**
Change the SHA of the image in the `vars.mk` file
Add a e2e test which build a local image and try to scan this image with the containerized Snyk Provider

**- How to verify it**
e2e test should pass 
On linux : 
```
$ docker build -f ./e2e/testdata/Dockerfile -t local:build .

# when the image have been built 
$ docker scan local:build
...
Organization:      docker-desktop-test
Package manager:   apk
Project name:      docker-image|local
Docker image:      local:build
Platform:          linux/amd64
Licenses:          enabled

Tested 14 dependencies for known issues, found 15 issues.
```

**- A picture of a cute animal (not mandatory)**

image

### CODE REVIEW

File: e2e/scan_test.go [hunk 1]
```diff
@@ -394,6 +395,27 @@ func TestScanWithContainerizedSnyk(t *testing.T) {
 	}
 }
 
+func TestScanLocalImageWithContainerizedSnyk(t *testing.T) {
+	if runtime.GOOS == "windows" || runtime.GOOS == "darwin" {
```
Comment (chris-crone) [inline e2e/scan_test.go:399]: nit:
```suggestion
	if runtime.GOOS != "linux" {
```

**Review by chris-crone — APPROVED** [review]
LGTM

**Review by gtardif — APPROVED** [review]
